=== AnnAiko/pojo/Задание 3/Schema.xsd
<?xml version="1.0"?>

<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified"
        targetNamespace="http://www.example.com/employments"
        xmlns:tns="http://www.example.com/employments"> 

    <element name="employments"> 
        <complexType>
            <sequence>
                <element name="employment"
                         type="tns:Employment"
                         minOccurs="2"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Employment">
        <sequence>
            <element name="countStudent" type="integer" />
            <element name="subject" type="tns:Subject" />
            <element name="teacher" type="tns:Teacher"/>
        </sequence>
        <attribute name="group" use="optional" default="PI-1-16" >
            <simpleType>
                <restriction base="string">
                    <enumeration value="PI-1-16"></enumeration>
                    <enumeration value="ISP-1-17"></enumeration>
                    <enumeration value="TPS-1-18"></enumeration>
                    <enumeration value="IS-1-15"></enumeration>
                    <enumeration value="BI-1-18"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Subject">
        <sequence>
            <element name="nameSub" >
                <simpleType> 
                    <restriction base="string">
                        <enumeration value="Math"></enumeration>
                        <enumeration value="Literature"></enumeration>
                        <enumeration value="Physics"></enumeration>
                        <enumeration value="History"></enumeration>
                    </restriction>
                </simpleType>     
            </element> 
            <element name="time" >
                <simpleType>
                    <restriction base="string">
                        <enumeration value="Monday"></enumeration>
                        <enumeration value="Tuesday"></enumeration>
                        <enumeration value="Wednesday"></enumeration>
                        <enumeration value="Thursday"></enumeration>
                        <enumeration value="Friday"></enumeration>
                        <enumeration value="Saturday"></enumeration>
                    </restriction>
                </simpleType>
            </element> 
            <element name="audience" type="string" /> 
        </sequence>
    </complexType>
    <complexType name="Teacher">
        <sequence>
            <element name="fio" type="string" />
            <element name="countPairTime" type="integer" /> 
        </sequence>
    </complexType>
</schema>

=== AnnAiko/pojo/Задание 3/newXMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
-->
<employments
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.example.com/employments'
    xsi:schemaLocation='http://www.example.com/employments Schema.xsd'>
    <employment group="PI-1-16">
        <countStudent>18</countStudent>
        <subject>
            <nameSub>Math</nameSub>
            <time>Tuesday</time>
        </subject>
        <teaher>
            <fio>Иванов Иван Иванович</fio>
            <countPairTime>2</countPairTime>
        </teaher>
    </employment>
    <employment group="ISP-1-17">
        <countStudent>25</countStudent>
        <subject>
            <nameSub>Literature</nameSub>
            <time>Friday</time>
        </subject>
        <teaher>
            <fio>Силоров Сергей Михайлович</fio>
            <countPairTime>3</countPairTime>
        </teaher>
    </employment>

</employments>
